- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: sa-banking-container
        image: malay442/sa-banking:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"


